// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import Login from './Components/Login';
import Home from './Components/Home';

const App = () => {
  return (
    <Router>
      <Routes>
        <Route path="/login" element={<Login />} />
        <Route path="/home" element={<Home />} />
        <Route path="/" element={<Login />} />  {/* Default to login */}
      </Routes>
    </Router>
  );
};

export default App;
